services:
  postgres:
    image: postgres:16-alpine
    container_name: pai-sql-agent-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pai_sql_agent
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pai_sql_agent"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    container_name: pai-sql-agent-app
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/pai_sql_agent
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SGIS_API_KEY=${SGIS_API_KEY:-}
      - SGIS_SECRET_KEY=${SGIS_SECRET_KEY:-}
      - LOG_LEVEL=INFO
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["8000:8000"]
    restart: unless-stopped
    # command는 Dockerfile의 CMD 사용 → 따로 안 써도 됨

volumes:
  postgres_data:
