services:
  postgres:
    image: postgres:16-alpine
    container_name: pai-sql-agent-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pai_sql_agent
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pai_sql_agent"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    container_name: pai-sql-agent-app
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/pai_sql_agent
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SGIS_SERVICE_ID=${SGIS_SERVICE_KEY:-}  # 수정
      - SGIS_SECURITY_KEY=${SGIS_SECURIT_KEY:-}  # 수정
      - LOG_LEVEL=INFO
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["8000:8000"]
    restart: unless-stopped

  streamlit:
    build: .
    container_name: pai-sql-agent-streamlit
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/pai_sql_agent
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SGIS_SERVICE_ID=${SGIS_SERVICE_KEY:-}  # 수정
      - SGIS_SECURITY_KEY=${SGIS_SECURIT_KEY:-}  # 수정
      - LOG_LEVEL=INFO
    depends_on:
      - app
    ports: ["8501:8501"]
    command: ["streamlit", "run", "webapp/streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    restart: unless-stopped

volumes:
  postgres_data: